/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://fonts.googleapis.com/css2?family=Red+Hat+Display:wght@500;700;900&display=swap'
          rel='stylesheet'
        />
      </Head>
      <div className='flex items-center justify-center h-screen bg-pale-blue relative -z-20'>
        <div className='absolute top-0 h-64 w-full -z-10 '>
          <img
            className='h-full w-full'
            src='/images/pattern-background-desktop.svg'
            alt=''
          />
        </div>
        <div className='flex items-center justify-center bg-white rounded-lg flex-col w-[20rem] md:w-[25rem]  '>
          <div className='overflow-hidden rounded-t-lg'>
            <img src='/images/illustration-hero.svg' alt='' />
          </div>
          <div className='flex flex-col gap-4  text-center p-6 md:p-10 '>
            <div className='font-bold text-2xl md:text-3xl text-dark--blue'>
              Order Summary
            </div>
            <div className='text-desaturated-blue text-sm'>
              You can now listen to millions of songs, audiobooks, and podcasts
              on any device anywhere you like!
            </div>
            <div className='flex justify-between p-3 md:p-6  items-center bg-very-pale-blue rounded-lg'>
              <div className='flex gap-4'>
                <img src='/images/icon-music.svg' alt='' />
                <div>
                  <div>Annual Plan</div>
                  <div className='text-desaturated-blue'>$59.99/year</div>
                </div>
              </div>
              <div>Change</div>
            </div>
            <button className='px-10 md:px-20 rounded-lg text-white py-2 bg-bright-blue'>
              Proceed to Payment
            </button>
            <div className='text-desaturated-blue font-semibold shadow-gray-400 text-sm'>
              Cancel Order
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
